<br>
<center>
<form action=addmb.php method=post>
<table border=1 cellspacing=0>
<th colspan=4>Create a new message board</th>
<tr>
<td>Subject</td>
<td colspan=3><input type=text name=subject size=70></td>
</tr>
<tr>
<td rowspan=2>Level</td>
<td align=center>Read</td>
<td align=center>Write</td>
<td align=center>Admin</td>
</tr>
<tr>
<td align=center><input type=text name=read></td>
<td align=center><input type=text name=write></td>
<td align=center><input type=text name=admin></td>
</tr>
<tr>
<td colspan=4 align=right><input type=submit name=action value=Post></td>
</tr>
</table>	
</form>
</center>
