<h2>BEAGLE Visualizer: A Web interface to visualize and analyze Open BEAGLE files</h2>

<p>BEAGLE Visualizer is a Web interface to visualize and analyse XML outputs given by the <a href="http://beagle.gel.ulaval.ca">Open BEAGLE</a> evolutionary computation framework. It gives detailed output such the fitness statistics vs time, individuals visual representation and population visual synthesis. All figures are generated in <a href="http://www.w3.org/Graphics/SVG">SVG</a>; you may need to install a plug-in such the one of <a href="http://www.adobe.com/svg">Adobe</a> to be able to see them in your favorite Web browser.</p>
 
<p>If you don't have an account yet, create one <a href=index.php?request=register>here</a>. Once it's done, <a href=index.php?request=login>login</a> and upload some file to generate a report like <a href=samples/onemax/>this one (OneMax with GA)</a> or <a href=samples/symbreg/>this one (symbolic regression with GP)</a>. Have fun playing with the different preferences!</p>

<p>Please note the BEAGLE Visualizer is still in an alpha development stage. It is offer with no warranty of any kind, more specifically on the data you put in the system. As the system evolves and improves, changes may need to clean-up the files or profiles without notification. You are warned!</p>
 
<p>BEAGLE Visualizer is an open source project. You can download the source code of BEAGLE Visualizer from the project page on <a href="http://sourceforge.net/projects/beagle">sourceforge</a>. From these sources, you are free to compile the command-line tools for local usage, or to install a mirror of the Web interface. If you are interested to contribute to the improvement of the system in any ways, contact us.</p>

<a href=mailto:cgagne@gel.ulaval.ca>Christian Gagn&eacute;</a><br>
<a href=mailto:pbnadeau@gel.ulaval.ca>Patrick-Emmanuel Boulanger-Nadeau</a><br>
<a href=mailto:gravel03@gel.ulaval.ca>Vincent-Olivier Gravel</a><br>
